language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install travis-sphinx

script:
  - travis-sphinx --source=source build

after_success:
  - travis-sphinx deploy
