language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install travis-sphinx

script:
  - sphinx-build -Wn -b html source target/doc/build

after_success:
  - travis-sphinx deploy
